version: '3'
# starts 2 docker containers with minio server instances
services:
  minio1:
    image: quay.io/minio/minio
    volumes:
      - data1:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    networks:
      - minio-net
    command: server http://minio{1...2}/data --console-address ":9090"

  minio2:
    image: quay.io/minio/minio
    volumes:
      - data2:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    networks:
      - minio-net
    command: server http://minio{1...2}/data --console-address ":9090"

  minio_nginx:
    image: nginx:1.13.9-alpine
    restart: always
    ports:
      - ${PORT_S3_SERVICE}:9000/tcp
      - ${PORT_WEB_SERVICE}:9090
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./minio.conf:/etc/nginx/conf.d/default.conf:ro
    links:
      - minio1
      - minio2
    networks:
      - minio-net

volumes:
  data1:
  data2:

networks:
  minio-net:
    driver: bridge